apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: estudos-k8s-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: estudos-k8s
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20